language: python
python:
  - "2.7"
install:
  # Pull down toplevel repo
  - git clone https://github.com/TipoftheHats/donation-tracker-toplevel toplevel
  - cd toplevel

  # Install custom django-paypal
  - git clone https://github.com/GamesDoneQuick/django-paypal.git
  - cd django-paypal && git checkout gdqversion && python setup.py install && cd ..

  # Pull donation tracker and install
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git tracker
  - cd tracker
  - git checkout -qf $TRAVIS_COMMIT
  - pip install -r requirements.txt
  - cd ../..

script:
  - cd toplevel && cp example_local.py local.py && python manage.py test
