language: python
python:
  - "2.7"
install:
  - git clone https://github.com/TipoftheHats/donation-tracker-toplevel toplevel
  - cd toplevel
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git tracker
  - cd tracker
  - git checkout -qf $TRAVIS_COMMIT
  - pip install -r requirements.txt
  - cd ../..
script:
  - cd toplevel && cp example_local.py local.py
  - python manage.py test
